server.port=8761
spring.application.name=eureka-discovery-server

# This IS the discovery server — it does not register itself or fetch from another
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
